[[conn]]
type = "mysql"
name = "sample"
user = "root"
host = "localhost"
port = 3306

[[conn]]
type = "postgres"
user = "postgres"
host = "localhost"
port = 5432

[[conn]]
type = "postgres"
user = "postgres"
host = "localhost"
port = 5432
database = "dvdrental"
