name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  release:
    name: Cargo publish
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v1
      - run: cargo login ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      - run: cargo publish
